<?php

use DigitalPolygon\Polymer\Environment\EnvironmentDetectorBase;
use DigitalPolygon\Polymer\Environment\AcquiaEnvironmentDetector;
use DigitalPolygon\Polymer\Environment\PantheonEnvironmentDetector;

/**
 * @file
 * Generated by Polymer.
 */

 /**
 * Site path.
 *
 * @var string $site_path
 * This is always set and exposed by the Drupal Kernel.
 */
$site_name = str_replace('sites/', '', $site_path);

$settings_files = [];

// Default global settings.
// @todo Add polymer specific settings file as needed.
$polymer_settings_files = [];
if ($polymer_settings_files) {
    foreach ($polymer_settings_files as $polymer_settings_file) {
        $settings_files[] = __DIR__ . "/$polymer_settings_file.settings.php";
    }
}

// Custom global and site-specific settings.
$settings_files[] = DRUPAL_ROOT . '/sites/settings/global.settings.php';
$settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings/includes.settings.php";

if (EnvironmentDetectorBase::isCiEnv()) {
    // Custom global and site-specific CI settings.
    $settings_files[] = DRUPAL_ROOT . "/sites/settings/ci.settings.php";
    $settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings/ci.settings.php";
}

// Local global and site-specific settings.
if (AcquiaEnvironmentDetector::isLocalEnv() || PantheonEnvironmentDetector::isLocalEnv()) {
    $settings_files[] = DRUPAL_ROOT . '/sites/settings/local.settings.php';
    $settings_files[] = DRUPAL_ROOT . "/sites/$site_name/settings/local.settings.php";
}

foreach ($settings_files as $settings_file) {
    if (file_exists($settings_file)) {
      // phpcs:ignore
      require $settings_file;
    }
}
