#!/usr/bin/env bash

set -e

# This script initializes the project.

ddev stop -OR
ddev start

rm -rf vendor composer.lock
ddev exec -- composer install --no-interaction

ddev build-docs
# Open docs in browser.
ddev launch :444
