name: CI

on:
  push:
    branches: [0.x]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [0.x]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
    code_guidelines:
      name: Code Guidelines
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          php_version: [8.1, 8.2, 8.3]
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.32.0
        with:
          php-version: ${{ matrix.php_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Run PHP_CodeSniffer
        run: composer cs

      - name: Lint
        run: composer lint

      - name: Run PHPStan
        run: composer sa
