name: Deploy Pages

on:
  push:
    branches: [0.x]
    tags: ["0.*"]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Polymer Documentation Bot"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs==1.5.3 \
            mkdocs-material \
            mike \
            mkdocs-git-authors-plugin \
            mkdocs-redirects \
            mkdocs-git-revision-date-localized-plugin \
            pymdown-extensions \
            git+https://gitlab.com/blacs30/mkdocs-edit-url.git;
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.32.0
      - name: Generate docs
        run: |
          composer install --no-interaction
          bin/polymer mk:docs
      - name: Mike alias
        run: mike alias 0.x latest --update-aliases
      - name: Mike set-default
        run: mike set-default latest
      # See https://github.com/jimporter/mike?tab=readme-ov-file#building-your-docs
      - name: Mike deploy
        run: mike deploy --push ${GITHUB_REF_NAME}
